export enum Estatus {
    ACTIVO = "ACTIVO",
    INACTIVO = "INACTIVO",
    ELIMINADO = "ELIMINADO",
    PENDIENTE = "PENDIENTE",
    CANCELADO = "CANCELADO",
    LIQUIDADO = "LIQUIDADO",
    PAGADO = "PAGADO",
    PAGADA = "PAGADA",
    NO_PAGADO = "NO PAGADO",
    NO_PAGADA = "NO PAGADA",
    AL_CORRIENTE = "AL CORRIENTE",
    CON_INTERES = "CON INTERES",
    CON_INTERESES = "CON INTERESES",
    NO_DISPONIBLE = "NO DISPONIBLE",
    DISPONIBLE = "DISPONIBLE",
    VENDIDO = "VENDIDO"
}